# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgboard', '0004_msgpost_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgpost',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
